 name: Battle-Royal
 version: 1.3.3.7
 description: Battle-Royal
 authors: [Relic] 
 
 main: net.relic.battleroyale.battleroyale
 
 
 commands:
    help:
        description: help command
    arena:
        description: arena command